input {
  udp {
    port => 5003
    type => "proxy_event"
  }
}

filter {
  if [type] == "proxy_event" {

    grok {
      match => {
        "message" => "<%{NUMBER:priority}>%{MONTH:month} +%{MONTHDAY:day} %{TIME:time} %{HOSTNAME:source_name} proxy: %{WORD:method} %{URI:url} %{NUMBER:status} %{NUMBER:bytes} %{IP:source_ip}"
      }
    }

    mutate {
      convert => { "status" => "integer" }

      add_field => {
        "event_category" => "web"
        "event_action" => "%{method}"
        "source_type" => "proxy"
        "log_source" => "proxy"
        "source.ip" => "%{source_ip}"
        "http.request.method" => "%{method}"
        "url.original" => "%{url}"
        "http.response.status_code" => "%{status}"
      }

      remove_field => ["url"]
    }

    if [status] and [status] >= 400 {
      mutate {
        add_field => {
          "event_type" => "proxy_request_error"
          "severity" => "medium"
        }
      }
    } else {
      mutate {
        add_field => {
          "event_type" => "proxy_request"
          "severity" => "low"
        }
      }
    }
  }
}

output {
  if [type] == "proxy_event" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "events-proxy-%{+YYYY.MM.dd}"
    }

    stdout {
      codec => rubydebug
    }
  }
}