input {
  udp {
    port => 5002
    type => "windows_event"
  }
}

filter {
  if [type] == "windows_event" {
    grok {
      match => {
        "message" => "<%{NUMBER:syslog_priority}>%{MONTH:month} +%{MONTHDAY:day} %{TIME:time} %{HOSTNAME:source_name} Security: EventID=%{NUMBER:event_id} User=%{USERNAME:username} SourceIP=%{IP:source_ip} Action=%{WORD:action}"
      }
    }

    mutate {
      lowercase => ["action"]

      add_field => {
        "event_category" => "authentication"
        "event_action" => "%{action}"
        "source_type" => "windows"
        "log_source" => "windows_event_log"
        "source.ip" => "%{source_ip}"
        "windows.event_id" => "%{event_id}"
        "windows.username" => "%{username}"
      }
    }

    if [action] == "failed" {
      mutate {
        add_field => {
          "event_type" => "windows_login_failed"
          "severity" => "medium"
        }
      }
    } else {
      mutate {
        add_field => {
          "event_type" => "windows_login"
          "severity" => "low"
        }
      }
    }
  }
}

output {
  if [type] == "windows_event" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "events-windows-%{+YYYY.MM.dd}"
    }

    stdout {
      codec => rubydebug
    }
  }
}